"""added new trips status field

Revision ID: d29c2833e9cc
Revises: 20260406_commute_posts
Create Date: 2026-04-06 00:44:01.073433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd29c2833e9cc'
down_revision: Union[str, None] = '20260406_commute_posts'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('status', sa.String(length=20), nullable=True))
    op.execute("UPDATE trips SET status = 'pending' WHERE status IS NULL")
    op.alter_column('trips', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trips', 'status')
    # ### end Alembic commands ###
